// <auto-generated />
using System;
using ApiMetasAnalistas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMetasAnalistas.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMetasAnalistas.Models.Analyst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MetaDiaria")
                        .HasColumnType("numeric(2, 0)")
                        .HasColumnName("meta_diaria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nome");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("int")
                        .HasColumnName("regiao_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("analysts");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("int")
                        .HasColumnName("regiao_id");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Occurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalistaId")
                        .HasColumnType("int")
                        .HasColumnName("analista_id");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("Tipo")
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.ToTable("occurrences");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalystId")
                        .HasColumnType("int")
                        .HasColumnName("analista_id");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fechamento");

                    b.HasKey("Id");

                    b.HasIndex("AnalystId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Analyst", b =>
                {
                    b.HasOne("ApiMetasAnalistas.Models.Region", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Holiday", b =>
                {
                    b.HasOne("ApiMetasAnalistas.Models.Region", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Occurrence", b =>
                {
                    b.HasOne("ApiMetasAnalistas.Models.Analyst", "Analista")
                        .WithMany()
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analista");
                });

            modelBuilder.Entity("ApiMetasAnalistas.Models.Ticket", b =>
                {
                    b.HasOne("ApiMetasAnalistas.Models.Analyst", "Analyst")
                        .WithMany()
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");
                });
#pragma warning restore 612, 618
        }
    }
}
